apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fuse-bookinfo-ratings
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
       paths:
       - path: /fuse/ratings(/|$)(.*)
         pathType: Prefix
         backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.ratings.port }}