apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: {{ .Values.ingress.serviceType }}
  ports:
  - protocol: TCP
    port: {{ .Values.ratings.port }}
  selector:
    app: {{ .Release.Name }}